### ISSUE TITLE
Meshes are colored by the color of objects added to the viewer when moving the camera

### ISSUE THREAD

**Issue by GaloMALDONADO** [humanoid-path-planner/gepetto-viewer#29]
When adding color to one object (i.e. an sphere using addSphere) in the viewer, all my meshes take this color.
When adding  more than one colored object (each object has a different color), the meshes take these colors and the color change when moving the camera .

**Comment by jcarpent** [comment]
This bug comes from OSG and not from Gepetto-Viewer. Closing issue.
