### ISSUE TITLE
devel -> master & release

### ISSUE THREAD

**Issue by olivier-stasse** [humanoid-path-planner/gepetto-viewer#32]
Dear all,
Will you be ok with merging devel into master,
and thinking about a release (the tag for v1.0.0 is 03/2015...)

Best,
Olivier.

**Comment by florent-lamiraux** [comment]
We need to check that the devel branch is compatible with all other master branches.
I will do it.

**Comment by jmirabel** [comment]
I agree with you @florent-lamiraux, though it is very unlikely that there is any problem. I merged master and devel branches not so long ago and there are very few changes in the viewer.

**Comment by olivier-stasse** [comment]
Do you think it would be worthwhile to write a set of unitary tests to check if the API is broken ?

**Comment by olivier-stasse** [comment]
This would avoid testing over all master branches...

**Comment by jmirabel** [comment]
Adding tests would be useful but I'm not sure how easy it is to automate tests on a viewer... I'm not sure what the best approach is. Maybe it would be easier to do this in the `gepetto-viewer-corba` package.

**Comment by olivier-stasse** [comment]
@jmirabl In this case it would consists simply on calling each method for each class.
Modification of the API woud automatically break the tests compilation ...

**Comment by jmirabel** [comment]
Oh yes, I did not understand it this way.
It should help to keep backward compatibility.

**Comment by florent-lamiraux** [comment]
I pushed release 1.1.0 on trac.laas.fr
I did the same for gepetto-viewer-corba.

**Comment by olivier-stasse** [comment]
Dear Florent,
Thanks a lot.
Could you push the tags on the github repository ?
