### ISSUE TITLE
intergration inside robotpkg

### ISSUE THREAD

**Issue by MaximilienNaveau** [humanoid-path-planner/gepetto-viewer#48]
In robotpkg it seems that the dependance of this package to robotpkg-omniorbpy is not set properly.
It looks like one have to install it separately to make the viewer work.

**Comment by florent-lamiraux** [comment]
Can you be more accurate ? Which repository of robotpkg ? There is now one in humanoid-path-planner, there is robotpkg-wip.

**Comment by nmansard** [comment]
Is this issue still problematic? If not, @MaximilienNaveau, could you close it?
