### ISSUE TITLE
error in window-manager.cpp during install

### ISSUE THREAD

**Issue by Bilalhmd** [humanoid-path-planner/gepetto-viewer#55]
the error returned 
gepetto-viewer/src/window-manager.cpp:420:12: error: no member named 'get' in 'osg::Matrixd'
    matrix.get(rot);

**Comment by jmirabel** [comment]
There are two problems:
- `Matrixd::get` is deprecated and is only present if OSG was compiled with USE_DEPRECATED_API. I will replace the call.
- your version seems old. The line you mention is now at line 542.
